seed: 1
device: auto
sequence_length: 5
trainset_dir: "${DATA_ROOT}/train"
valset_dir: "${DATA_ROOT}/DAVIS_val"
noise_csv: "dataloaders/predicted_labels.csv"
external_shift_net_dir: "external/Shift-Net"
teacher_arch: gshift_denoise1
output_dir: "artifacts/teacher"

batch_size: 1
patch_size: 160
iterations: 100000
num_workers: 2
num_prefetch_queue: 4
val_sequence_length: 25
val_interval: 1000
scheduler_step_interval: 1000
noise_seed: 1

lr: 0.0001

scheduler:
  name: StepLR
  step_size: 20
  gamma: 0.6
